services:
  production-project:
    build: .
    container_name: production-project
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true